version: '3'

services:
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: lostincairo
      MONGO_INITDB_ROOT_PASSWORD: cairoexplorer
    ports:
    - 27017:27017
    volumes:
    - ./_docker/apibara_mongodb:/data/db

  indexer:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command:
    - start
    - --mongo-url
    - "mongodb+srv://lostincairo:cairoexplorer@cluster0.8m5ok7q.mongodb.net/?retryWrites=true&w=majority"
    environment:
      PYTHONUNBUFFERED: "1"
    links:
    - mongo