version: '3'

services:
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: lostincairo
      MONGO_INITDB_ROOT_PASSWORD: cairoexplorer
    ports:
    - 27017:27017
    volumes:
    - ./_docker/apibara_mongodb:/data/db
